title = "Social Force Basic Config"

[scene]
enable_group = false
agent_radius = 0.1
# the maximum speed doesn't exceed 1.3x initial speed
max_speed_multiplier = 1.3

[desired_force]
factor = 1.0

# The relaxation distance of the goal
goal_threshold = 0.2
# How long the relaxation process would take
relaxation_time = 0.5


[social_force]
factor = 0.5

# Moussaid-Helbing 2009
# relative importance of position vs velocity vector
lambda_importance = 2.0
# define speed interaction
gamma = 0.35
n = 2
# define angular interaction
n_prime = 3

[obstacle_force]
factor = 2.0

# the standard deviation of obstacle force
sigma = 0.1
# threshold to trigger this force
threshold = 1.0